# This OpenAPI file is fragment and should not be distributedusers separately

openapi: 3.0.3
info: { title: "<FRAGMENT>", version: "<FRAGMENT>" }
paths: { /: {get: {responses: { "418": { description: FRAGMENT } } } } }

components:
  schemas:
    ApplicationBaseInfo:
      type: object
      properties:
        name:
          type: string
          description: Meno Aplikacie
        version:
          type: string
          description: Verzia Aplikacie

    ApplicationUserInfo:
      type: object
      allOf:
        - $ref: '#/components/schemas/ApplicationBaseInfo'
        - type: object
          properties:
            userName:
              type: string
              description: Meno uzivatela ktory vytvoril build

    ApplicationBuildInfoResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ApplicationUserInfo'
        - type: object
          properties:
            buildedBy:
              type: string
              description: Datum a cas buildovania

    ApplicationBuildInfo:
      type: object
      allOf:
        - $ref: '#/components/schemas/ApplicationUserInfo'
        - type: object
          properties:
            buildedIn:
              type: string
              description: Datum a cas buildovania
            arifactGroup:
              type: string
              description: Group-a Artefaktu Repozitara
            artifactName:
              type: string
              description: Meno Artefaktu Repozitara
            gitHash:
              type: string
              description: GIT HASH pre identifikaciu zdroja distribucie
