openapi: 3.0.3
info:
  title: Spring JPA Sample User API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/

paths:
  /v1/users:
    $ref: '../services/user-services.yml#/paths/~1users'
  /v1/users/{userName}:
    $ref: '../services/user-services.yml#/paths/~1users~1{firstName}'

