server:
  port: 8080
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
spring:
  jackson:
    date-format: vd.sandbox.spring.jpa.invoker.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jpa-user
    password: jpa-user-password
    url: jdbc:mysql://localhost:3306/spring-jpa-test?createDatabaseIfNotExist=true

# Original application.properties file
#springfox.documentation.swagger.v2.path=/api-docs
#server.port=8080
#spring.jackson.date-format=vd.sandbox.spring.jpa.invoker.RFC3339DateFormat
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.show-sql=true
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=jpa-user
#spring.datasource.password=jpa-user-password
#spring.datasource.url=
#  jdbc:mysql://localhost:3306/spring-jpa-test?createDatabaseIfNotExist=true
