server:
  port: 8080
  servlet:
    context-path: /jasyp

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    vd.samples: DEBUG

cors:
  allow:
    all:
      origins: true

# Date time settings
cp:
  datetime:
    default:
      zone: Europe/Bratislava
    validity:
      interval:
        months: 12

spring:
  profiles:
      active: oneWay
#      active: twoWay
  liquibase:
    enabled: true
    contexts: oneWay,twoWay
#        change-log: classpath:liquibase/liquibase-change-log.yaml
    change-log: classpath:liquibase/liquibase-changelog-master.xml
    drop-first: false # Nastavit na true v pripade, ze treba vymazat databazu
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  jasypt:
    passphrase: nejaka_hlupa_fraza_na_kryptovanie_a_co_najdlhsia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: jpa-user
#    password: jpa-user-password
    url: jdbc:mysql://localhost:3306/spring-jpa-test?createDatabaseIfNotExist=true
