openapi: 3.0.3
info:
  title: SpringBoot Oracle Hikary Pool with Liquibase
  version: 1.0.0
servers:
  - url: http://localhost:8080/

paths:
  /v1/app-info/buildInfo:
    $ref: 'services/app-api-info.yml#/paths/~1app-info~1buildInfo'
  /v1/app-info/buildUser:
    $ref: 'services/app-api-info.yml#/paths/~1app-info~1buildUser'

