# Use the official Maven image to build
FROM jelastic/maven:3.9.5-openjdk-21 AS build
# Set the working dir
WORKDIR /spring-mapstruct
MAINTAINER Vaclav Demcak <vaclav.demcak@gmail.com>
# Copy the pom and download dependencies / could be replaced by git clone
COPY pom.xml .
COPY src ./src
COPY api-definition ./api-definition

# add git
RUN cat /etc/os-release
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
#RUN yum update
RUN yum -y install git
RUN git config --global user.email "builder@vaclav.com"
RUN git config --global user.name "Builder Builderovic"
RUN git init
RUN git add .
RUN git commit -m "Build commit"
RUN mvn clean package -DskipTests

# Use a smaller base image to run
FROM openjdk:21-jdk-slim
# Set th working dir
WORKDIR /spring-mapstruct
# Copy the jar file from the previous stage
COPY --from= build /spring-mapstruct/target/*.jar spring-mapstruct-1.0-SNAPSHOT.jar
# Expose the application port
EXPOSE 8989

# Run the application
ENTRYPOINT ["java", "-jar", "spring-mapstruct-1.0-SNAPSHOT.jar"]