version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: password987
      MYSQL_PASSWORD: password987
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword987"]
      timeout: 5s
      retries: 2


  springboot-app:
    container_name: Spring-Mapstruct
    image: 'spring-mapstruct:latest'
    restart: on-failure
    build: .
    ports:
      - "8989:8989"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password987
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy